---
## Exercício 1
---

In [2]:
import numpy as np

v1 = [10,20,30,20,10,1,0,2,5,0,20,1,4,0,20,20,20,30,40,11,44,55]
v2 = [1,25,50,41,5,20,10,23,5,10,20,13,4,20,100,20,50,35,40,4,55,55]

array = np.array(v1)
array2 = np.array(v2)

array

array([10, 20, 30, 20, 10,  1,  0,  2,  5,  0, 20,  1,  4,  0, 20, 20, 20,
       30, 40, 11, 44, 55])

---
## Exercício 2
---

In [3]:
A = np.arange(1, 101, 1)
print(A.sum())
print(A.std())

5050
28.86607004772212


In [4]:
B = [i/(i+1) for i in range(1, 101)]
B = np.array(B)
print(B.sum())
print(B.std())

95.80272149226137
0.06774293033775461


In [5]:
C = [(((-1)**i)*(i+1))/(3**i) for i in range(1,101)]
C = np.array(C)
print(C.sum())
print(C.std())

-0.4375
0.07616542440635383


---
## Exercício 3
---

In [6]:
import numpy as np

arrN20 = np.random.randn(20)
arrN20

array([ 1.20599315e+00, -1.79131314e+00,  2.15966422e+00, -7.06802219e-01,
        1.22442843e+00, -3.49440849e-01,  8.54600882e-01,  1.58054110e+00,
       -6.15519681e-01, -2.90017124e-02, -1.52172798e+00,  1.45499772e+00,
       -4.65528384e-01,  4.45374084e-04, -4.09297657e-01, -2.18046792e+00,
       -1.98583069e+00,  1.38707362e-01, -1.47166458e-01,  4.83567987e-01])

___
## Exercício 4
___

In [7]:
arrU20 = np.random.randint(-10,10, size = 20)
arrU20

array([ -2,  -3,  -3,  -8,  -2,   9,   0,  -3,   5,   2,  -5,   6,   9,
        -9, -10, -10,   8,  -6,   2,  -8], dtype=int32)

___
## Exercício 5
___

In [8]:
print(arrN20*10)

[ 1.20599315e+01 -1.79131314e+01  2.15966422e+01 -7.06802219e+00
  1.22442843e+01 -3.49440849e+00  8.54600882e+00  1.58054110e+01
 -6.15519681e+00 -2.90017124e-01 -1.52172798e+01  1.45499772e+01
 -4.65528384e+00  4.45374084e-03 -4.09297657e+00 -2.18046792e+01
 -1.98583069e+01  1.38707362e+00 -1.47166458e+00  4.83567987e+00]


___
## Exercício 6
___

Não é o que se espera de um produto vetorial interno que nos retorna um escalar. Esse resutado nos retorna um vetor.

In [9]:
arrN20 * arrU20

array([-2.41198631e+00,  5.37393941e+00, -6.47899265e+00,  5.65441775e+00,
       -2.44885687e+00, -3.14496764e+00,  0.00000000e+00, -4.74162329e+00,
       -3.07759841e+00, -5.80034247e-02,  7.60863991e+00,  8.72998631e+00,
       -4.18975545e+00, -4.00836676e-03,  4.09297657e+00,  2.18046792e+01,
       -1.58866455e+01, -8.32244174e-01, -2.94332915e-01, -3.86854389e+00])

___
## Exercício 7
___

In [10]:
MN = np.random.randn(5,10)
MN

array([[-0.6062807 ,  0.51403623, -0.35760522, -0.81582575, -0.23358974,
        -0.99354963, -0.81562647, -0.56545092, -0.77269453,  0.47292363],
       [-0.83734205,  1.24510255, -0.20737624,  0.55177677,  0.13224991,
        -1.95472712, -0.19072085,  2.09640708,  1.78742304,  0.86452787],
       [-1.22762037, -0.20041351, -0.86098696,  2.0043492 , -1.22578139,
         0.81320525,  0.00655123,  0.49498827, -0.45145343,  0.42880418],
       [ 0.0800183 , -1.34560941,  1.42000518,  0.26600963,  1.42337559,
         0.13624215,  0.44319531,  1.45574856, -0.05991534,  0.20704527],
       [ 1.17272179, -3.47493867, -0.37190794, -0.35516893,  1.31633217,
        -0.74287503, -0.92393951,  1.32656651, -0.05098596,  0.62151468]])

___
## Exercício 8
___

In [11]:
MU = np.random.randint(-10,60, size = (5,10))
MU

array([[ 16,  27,  28,  55,  36,  12,  29,  57, -10,  43],
       [ 32,  -1,  -9,   7,  39,  -6,  31,  18,   8,   8],
       [ 18,  -8,  12,  20,  35,  52,  22,  21,  36,  48],
       [ 24,  12,  34,   9,  25,  43,  -2,  11,  -7,  59],
       [ 34,   0,  53,  21,  36,  17,   9,  30,  21,  32]], dtype=int32)

___
## Exercício 9
___

In [12]:
for i in arrN20:
    if i > 0:
        print(i)

1.2059931537227164
2.1596642160742014
1.2244284340608984
0.8546008816648409
1.5805410955735963
1.4549977189805756
0.00044537408400402613
0.13870736239030615
0.4835679865342042


___
## Exercício 10
___

In [13]:
print(arrU20[5:11])

[ 9  0 -3  5  2 -5]


___
## Exercício 11
___

In [14]:
print(arrU20[1:])

[ -3  -3  -8  -2   9   0  -3   5   2  -5   6   9  -9 -10 -10   8  -6   2
  -8]


___
## Exercício 12
___

In [15]:
print(arrU20[:-1])

[ -2  -3  -3  -8  -2   9   0  -3   5   2  -5   6   9  -9 -10 -10   8  -6
   2]


___
## Exercício 13
___

In [16]:
M = np.array([[4, 3, 3, 4],  [4, 3, 3, 2],  [5, 3, 5, 5],  [5, 3, 3, 4]])
print(f'a) \n {M[1:,:]} \n')
print(f"b) \n {M[:-1,:]} \n")
print(f"c) \n {M[1:3,:]} \n")
print(f"c) \n {M[1:3,:-1]} \n")
print(f"d) \n {M[0:-1,1:4]} \n")
print(f"e) \n {M[:,1:-2]} \n")

a) 
 [[4 3 3 2]
 [5 3 5 5]
 [5 3 3 4]] 

b) 
 [[4 3 3 4]
 [4 3 3 2]
 [5 3 5 5]] 

c) 
 [[4 3 3 2]
 [5 3 5 5]] 

c) 
 [[4 3 3]
 [5 3 5]] 

d) 
 [[3 3 4]
 [3 3 2]
 [3 5 5]] 

e) 
 [[3]
 [3]
 [3]
 [3]] 



___
## Exercício 14
___

In [22]:
print(f'a) \n {M.sum(axis=1)} \n')
print(f"b) \n {M.sum(axis=0)} \n")

print(f"c) \n {M.sum()} \n")
print(f"d) \n {M.mean()} \n")

a) 
 [14 12 18 15] 

b) 
 [18 12 14 15] 

c) 
 59 

d) 
 3.6875 



___
## Exercício 15
___

In [24]:
## A
a = np.array([[2, 3], [1, -5]])
b = np.array([4, 2])
x = np.linalg.solve(a, b)
x

array([ 2., -0.])

In [25]:
## B
c = np.array([[1, 2, -3], [3, -1, 2], [2, 1, 1]])
d = np.array([1, 0, 2])
y = np.linalg.solve(c, d)
y

array([0.0625, 1.3125, 0.5625])

___
## Exercício 16
___

In [49]:
arr_paes = np.array(["frances","italiano","sirio","frances","sirio"])

arr_pesos = np.array([[3.0,2.8,10,3.0,3.23,3.0,2.8,3.0],   [5.0,5.3,4.95,4.9,5.23,5.,5.,6.],   [3.0,2.8,3.1,3.0,3.23,3.,3.,3.],   [6.0,6.8,6.1,6.0,6.23,5.8,5.9,6.],   [3.0,2.8,3.1,3.0,3.23,3.,3.1,3.]])
unique_paes = np.unique(arr_paes)

for i in unique_paes:
    media = arr_pesos[arr_paes == i].mean()
    variancia = arr_pesos[arr_paes == i].var()
    # print(f'Média do pão {i}: {media} \nVariancia do pão {i}: {variancia} \n')
    if variancia > media/2:
        print(f'[RESPONSE] O pão {i} precisa de uma nova amostra a ser coletada. \n')



[RESPONSE] O pão frances precisa de uma nova amostra a ser coletada. 



___
## Exercício 17
___

In [62]:
print(f'Média de todos o pães no primeiro dia de coleta: {arr_pesos[:,:1].mean()}')
print(f'Média de todos o pães no primeiro dia de coleta: {arr_pesos[:,-1:].mean()}')

Média de todos o pães no primeiro dia de coleta: 4.0
Média de todos o pães no primeiro dia de coleta: 4.2
