---
## Exercício 1
---

In [4]:
import numpy as np

v1 = [10,20,30,20,10,1,0,2,5,0,20,1,4,0,20,20,20,30,40,11,44,55]
v2 = [1,25,50,41,5,20,10,23,5,10,20,13,4,20,100,20,50,35,40,4,55,55]

array = np.array(v1)
array2 = np.array(v2)

array

array([10, 20, 30, 20, 10,  1,  0,  2,  5,  0, 20,  1,  4,  0, 20, 20, 20,
       30, 40, 11, 44, 55])

---
## Exercício 2
---

In [32]:
A = np.arange(1, 101, 1)
print(A.sum())
print(A.std())

5050
28.86607004772212


In [34]:
B = [i/(i+1) for i in range(1, 101)]
B = np.array(B)
print(B.sum())
print(B.std())

95.80272149226137
0.06774293033775461


In [35]:
C = [(((-1)**i)*(i+1))/(3**i) for i in range(1,101)]
C = np.array(C)
print(C.sum())
print(C.std())

-0.4375
0.07616542440635383


---
## Exercício 3
---

In [1]:
import numpy as np

arrN20 = np.random.randn(20)
arrN20

array([-0.59374269, -1.718373  , -1.206143  , -1.36095011, -0.55462992,
        1.72505174,  0.53983719, -1.10064784,  0.19849229, -0.87963153,
       -0.13976787, -0.4437838 ,  0.49046533,  0.49254182, -1.68875133,
       -0.44356653,  0.48702419, -0.10763633, -2.41890964, -0.82512585])

___
## Exercício 4
___

In [2]:
arrU20 = np.random.randint(-10,10, size = 20)
arrU20

array([ -9,   6,   7,  -4,   9,   2,  -3, -10,   0, -10,  -7, -10,   1,
        -6,   6,   1,   9,  -9,   3,  -1], dtype=int32)

___
## Exercício 5
___

In [4]:
print(arrN20*10)

[ -5.93742691 -17.18373003 -12.06142998 -13.6095011   -5.54629923
  17.25051736   5.39837192 -11.00647839   1.98492289  -8.79631526
  -1.39767867  -4.437838     4.90465334   4.92541821 -16.8875133
  -4.43566527   4.8702419   -1.07636331 -24.1890964   -8.25125846]


___
## Exercício 6
___

Não é o que se espera de um produto vetorial interno que nos retorna um escalar. Esse resutado nos retorna um vetor.

In [8]:
arrN20 * arrU20

array([  5.34368422, -10.31023802,  -8.44300099,   5.44380044,
        -4.9916693 ,   3.45010347,  -1.61951158,  11.00647839,
         0.        ,   8.79631526,   0.97837507,   4.437838  ,
         0.49046533,  -2.95525092, -10.13250798,  -0.44356653,
         4.38321771,   0.96872698,  -7.25672892,   0.82512585])

___
## Exercício 7
___

In [11]:
MN = np.random.randn(5,10)
MN

array([[-0.70395652,  0.26948211, -0.05461969,  0.32431376,  1.2489105 ,
        -0.94578528, -0.81447683, -1.56869075,  0.56307953, -2.04364307],
       [ 0.55053267,  1.08454454, -1.25526672,  0.01235653,  1.73582398,
         0.96298915,  1.02918691, -0.93585616,  0.01267903, -0.32234737],
       [-0.97151295, -0.18910786,  0.10092755, -0.85494796,  0.55430726,
         0.83567429, -1.1728359 ,  0.4179812 , -0.26810227,  0.70560501],
       [-0.79289249, -0.96265933, -0.04214764,  0.461249  , -0.17758039,
        -0.53013115, -0.82275358,  0.36802811, -0.18964868,  0.57416629],
       [-0.04532176, -0.87370739, -0.28308626,  1.30728532,  0.09132713,
        -0.74188912, -0.17139656, -0.90610113, -1.66495758, -0.32066845]])

___
## Exercício 8
___

In [12]:
MU = np.random.randint(-10,60, size = (5,10))
MU

array([[46, 45, 26, 39,  3, 33, 33, 39, 59, 37],
       [55, 24, 45, 45, 19, -9, 57, 55, 38, 38],
       [38, -4, 38, -1, 42, 28, 49,  8, 12, -1],
       [30,  2, 15, -3, 19, 46, 36, 12, 21, 39],
       [20, 28,  8, 56, 45,  5, 16,  3, 15, 57]], dtype=int32)

___
## Exercício 9
___

In [16]:
for i in arrN20:
    if i > 0:
        print(i)

1.7250517359429316
0.539837192220311
0.19849228868996485
0.4904653336673722
0.4925418207121796
0.4870241897603232


___
## Exercício 10
___

In [22]:
print(arrU20[5:11])

[  2  -3 -10   0 -10  -7]


___
## Exercício 11
___

In [28]:
print(arrU20[1:])

[  6   7  -4   9   2  -3 -10   0 -10  -7 -10   1  -6   6   1   9  -9   3
  -1]


___
## Exercício 12
___

In [29]:
print(arrU20[:-1])

[ -9   6   7  -4   9   2  -3 -10   0 -10  -7 -10   1  -6   6   1   9  -9
   3]


___
## Exercício 13
___

In [59]:
M = np.array([[4, 3, 3, 4],  [4, 3, 3, 2],  [5, 3, 5, 5],  [5, 3, 3, 4]])
print(f'a) \n {M[1:,:]} \n')
print(f"b) \n {M[:-1,:]} \n")
print(f"c) \n {M[1:3,:]} \n")
print(f"c) \n {M[1:3,:-1]} \n")
print(f"d) \n {M[0:-1,1:4]} \n")
print(f"e) \n {M[:,1:-2]} \n")

a) 
 [[4 3 3 2]
 [5 3 5 5]
 [5 3 3 4]] 

b) 
 [[4 3 3 4]
 [4 3 3 2]
 [5 3 5 5]] 

c) 
 [[4 3 3 2]
 [5 3 5 5]] 

c) 
 [[4 3 3]
 [5 3 5]] 

d) 
 [[3 3 4]
 [3 3 2]
 [3 5 5]] 

e) 
 [[3]
 [3]
 [3]
 [3]] 

